### ISSUE TITLE
字幕内容结尾是数字时会被省略

### ISSUE THREAD

**Issue by WAcry** [F-loat/caption2text#2]
举例
一个srt文件的部分内容为：
62
00:03:47,226 --> 00:03:54,156
in the past produced
fossils like Sts 5 and Sts 14

63
00:03:54,366 --> 00:03:58,636
which consists of a partial
skeleton, this innominate bone,
会被转换成：
in the past produced
fossils like Sts 5 and Sts which consists of a partial
skeleton, this innominate bone,

原文中的14被抹去了

**Comment by F-loat** [comment]
遇到其他问题可以再反馈
