### ISSUE TITLE
会把数字过滤掉...

### ISSUE THREAD

**Issue by hrk1205** [F-loat/caption2text#3]
最近应该是有更新了？
发现新版本会把一些数字过滤掉..

21
00:00:38,360 --> 00:00:40,450
  Popeyes went from getting 4000 tweets a day

22
00:00:40,450 --> 00:00:42,280
to 140,000.

这个放进去就会，自动把数字过滤掉...
用上面的转，就会看到问题..
之前好像也遇到过，会缺失字符，当时没注意，觉得可能是一个小问题..
今天又遇到同样的，所以来这里提交下...
第一次提交issues，不知道这样对不对... 哈

**Comment by F-loat** [comment]
这个项目 issue 可以随意点的

正则还是不太可靠谱，我先修复试试，有空找个语法解析的库改下

**Comment by F-loat** [comment]
目前可能要重启下浏览器才会更新缓存
