### ISSUE TITLE
不支持 SSA 文件

### ISSUE THREAD

**Issue by VincentGaoHJ** [F-loat/caption2text#5]
请问未来可否支持 SSA 文件？

**Comment by VincentGaoHJ** [comment]
格式：

[Script Info]
; // 此字幕由TimeM生成
; // 欢迎访问人人影视 http://www.YYeTs.net
Title:YYeTs
Original Script:YYeTs
Synch Point:1
ScriptType:v4.00+
Collisions:Normal
Timer:100.0000
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,方正黑体简体,21,&H00FFFFFF,&HF0000000,&H006C3300,&H00000000,0,0,0,0,100,100,0,0.00,1,2,1,2,5,5,2,134
[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:08.40,0:00:11.98,Default,NTP,0000,0000,0000,,{\c&H5353ff&\fs22\fn微软雅黑}人人影视 {\alpha&H1A&\c&H00FFFFFF}诚意奉献{\fs\b0}


截图：
![image](https://user-images.githubusercontent.com/33255924/128174574-0150fd25-b59b-4599-bf0d-0d1d7a8287c4.png)

**Comment by Monthlyaway** [comment]
你好，我是编程小白，请问怎么导入ass文件？我输入了 npm run serve 后没反应

**Comment by Monthlyaway** [comment]
'vue-cli-service' is not recognized as an internal or external command,
operable program or batch file.

**Comment by F-loat** [comment]
@Monthlyaway 直接访问 https://f-loat.github.io/caption2text/ 使用就可以

本地运行的话需要有 nodejs 环境，然后安装下依赖
